# Generated by Django 4.2.4 on 2023-08-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_last_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_code',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Время последнего сообщения'),
        ),
    ]
